name: Continuous Integration & Delivery
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: network-diagnostics-api

jobs:
  lint-and-sast:
    name: Code Quality & SAST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Ruff (Lint & Format Check)
        run: |
          ruff check .
          ruff format --check .

      - name: Run Mypy
        run: mypy src tests

      - name: Run Bandit
        run: bandit -c pyproject.toml -r src tests

      - name: Pip Audit
        uses: pypa/gh-action-pip-audit@v1.1.0
        with:
          inputs: requirements.txt

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: lint-and-sast
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          tags: ${{ env.IMAGE_NAME }}:ci-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Export Docker image
        run: docker save ${{ env.IMAGE_NAME }}:ci-${{ github.sha }} > /tmp/image.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: /tmp/image.tar
          retention-days: 3

  test-and-scan:
    name: Test & Image Scan
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: /tmp

      - name: Load Docker image
        run: docker load < /tmp/image.tar

      - name: Run Tests in Docker
        run: |
          docker run --rm ${{ env.IMAGE_NAME }}:ci-${{ github.sha }} pytest -v

      - name: Run Trivy (table)
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: '${{ env.IMAGE_NAME }}:ci-${{ github.sha }}'
          format: table
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Run Trivy (sarif)
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: '${{ env.IMAGE_NAME }}:ci-${{ github.sha }}'
          format: sarif
          output: 'trivy-results.sarif'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

  publish:
    outputs:
      image_tag: ${{ steps.set-tag.outputs.tag }}
    name: Publish Image
    runs-on: ubuntu-latest
    environment: production
    needs: test-and-scan
    if: >
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' &&
       github.event.pull_request.base.ref == 'main' &&
       contains(github.event.pull_request.labels.*.name, 'publish'))
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: /tmp

      - name: Load Docker image
        run: docker load < /tmp/image.tar

      - name: Set image tags
        id: set-tag
        shell: bash
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "tag=v0.1.${{ github.run_number }}-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            RAW_BRANCH="${{ github.head_ref }}"
            SAFE_TAG=$(echo "$RAW_BRANCH" | sed 's/[^a-zA-Z0-9]/-/g')
            echo "tag=test-$SAFE_TAG" >> $GITHUB_OUTPUT
          fi

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and Push
        run: |
          REGISTRY_IMAGE="${{ secrets.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}"

          docker tag ${{ env.IMAGE_NAME }}:ci-${{ github.sha }} $REGISTRY_IMAGE:${{ steps.set-tag.outputs.tag }}
          docker push $REGISTRY_IMAGE:${{ steps.set-tag.outputs.tag }}

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: production
    needs: publish
    env:
      IMAGE_TAG: ${{ needs.publish.outputs.image_tag }}
    if: github.event_name == 'push'
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /srv/network-diagnostics-api

            export REGISTRY="${{ secrets.DOCKER_REGISTRY }}"
            export IMAGE_NAME="network-diagnostics-api"

            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d

            docker image prune -f
